config/routes.rb
BtcjamClient::Application.routes.draw do

  match 'authenticated_calls/:api' => 'api#authenticated_calls', :as => :authenticated_calls
  match 'invest_call/:api' => 'api#invest_call', :as => :invest_call
  match 'reference_calls/:api' => 'api#reference_calls', :as => :reference_calls
  match 'multi_payment_calls' => 'api#multi_payment_calls', :as => :multi_payment_calls
  match 'open_calls/:api' => 'api#open_calls', :as => :open_calls
  match 'new_user_calls/:api' => 'api#new_user_calls', :as => :new_user_calls 
  match 'new_id_calls/:api' => 'api#new_id_calls', :as => :new_id_calls
  match 'new_addr_calls/:api' => 'api#new_addr_calls', :as => :new_addr_calls
  match 'new_credit_calls/:api' => 'api#new_credit_calls', :as => :new_credit_calls 
  match 'new_phone_calls/:api' => 'api#new_phone_calls', :as => :new_phone_calls
  match 'phone_confirmation_calls/:api' => 'api#phone_confirmation_calls', :as => :phone_confirmation_calls  
  match 'phone_resend_sms_calls/:api' => 'api#phone_resend_sms_calls', :as => :phone_resend_sms_calls
  match 'user_change_calls/:api' => 'api#user_change_calls', :as => :user_change_calls
  match 'withdraw_calls/:api' => 'api#withdraw_calls', :as => :withdraw_calls
  match 'credit_report_calls/:api' => 'api#credit_report_calls', :as => :credit_report_calls
  match 'new_listing_calls/:api' => 'api#new_listing_calls', :as => :new_listing_calls 
  match 'activate_listing' => 'api#activate_listing', :as => :activate_listing 
  match 'new_lead_listing_calls/:api' => 'api#new_lead_listing_calls', :as => :new_lead_listing_calls  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  resources :references
  resources :multi_payments
  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index 
    if signed_in?
      
      @statuses = SSLAccess::ssl_get("#{BTCJAM_APP_URL}/employment_statuses.json" )
      @nationalid_types = SSLAccess::ssl_get("#{BTCJAM_APP_URL}/nationalid_types.json" )
      
    end
  end
end

app/views/home/_activate_listing_form.html.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      .panel-title.text-center
        Activate Listing
        
    =form_tag( activate_listing_path(:listings), multipart: true) do
      .form-group.panel-body
        .row
          .col-md-4
            =label_tag "listing_id"
          .col-md-8
            =text_field_tag :listing_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "Signature Picture"
          .col-md-8
            =file_field_tag :signature
        %br/
        .text-center
          =submit_tag "Activate" , class: "btn btn-default" 

     

app/views/home/_checks_forms.html.haml
.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Identity check
      =form_tag( new_id_calls_path(:identity_checks), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "Name"
            .col-md-8
              =text_field_tag :name, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Gender"
            .col-md-8
              =text_field_tag :gender, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Date of Birth(YYYY-MM-DD)"
            .col-md-8
              =text_field_tag :dob , '',class: "form-control"
          .row
            .col-md-4
              =label_tag "National ID type"
            .col-md-8
          .row
            .col-md-4
              =label_tag "National Identification Number"
            .col-md-8
              =text_field_tag :nationalid, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Document Picture - front"
            .col-md-8
              =file_field_tag 'picture' 
          .row
            .col-md-4
              =label_tag "Document Picture - back"
            .col-md-8
              =file_field_tag 'picture_back' 
          .row
            .col-md-4
              =label_tag "Document Picture - with face"
            .col-md-8
              =file_field_tag 'picture_face' 
          %br/
          .text-center
            =submit_tag "Submit id check" , class: "btn btn-default" 
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Address check
      =form_tag( new_addr_calls_path(:addr_checks), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "Addres line 1"
            .col-md-8
              =text_field_tag :addr1, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Addres line 2"
            .col-md-8
              =text_field_tag :addr2, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "zip code"
            .col-md-8
              =text_field_tag :zip , '',class: "form-control"
          .row
            .col-md-4
              =label_tag "City"
            .col-md-8
              =text_field_tag :city, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "State"
            .col-md-8
              =text_field_tag :state, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Country"
            .col-md-8
              =text_field_tag :country, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Proof of address Picture"
            .col-md-8
              =file_field_tag 'picture' 
          %br/
          .text-center
            =submit_tag "Submit Address check" , class: "btn btn-default"
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Income check
      =form_tag( new_credit_calls_path(:credit_checks), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "SSN"
            .col-md-8
              =text_field_tag :ssn, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Home ownership"
            .col-md-8
              =check_box_tag :home_ownership, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Car Ownership"
            .col-md-8
              =check_box_tag :car_ownership , '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Annual Income"
            .col-md-8
              =text_field_tag :annual_income, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Employment Status"
            .col-md-8
          .row
            .col-md-4
              =label_tag "Credit Score"
            .col-md-8
              =text_field_tag :credit_score, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Proof of Income 1*"
            .col-md-8
              =file_field_tag 'picture1' 
          .row
            .col-md-4
              =label_tag "Proof of Income 2"
            .col-md-8
              =file_field_tag 'picture2' 
          .row
            .col-md-4
              =label_tag "Proof of Income 3"
            .col-md-8
              =file_field_tag 'picture3' 
          %br/
          .text-center
            =submit_tag "Submit Credit check" , class: "btn btn-default"
.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Phone check
        =form_tag( new_phone_calls_path(:phone_checks), multipart: true) do
          .form-group.panel-body
            .row
              .col-md-4
                =label_tag "Phone"
              .col-md-8
                =text_field_tag :phone, '',class: "form-control"
            %br/
            .text-center
              =submit_tag "Submit Phone check" , class: "btn btn-default"
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Resend SMS
        =form_tag( phone_resend_sms_calls_path(:phone_checks), multipart: true) do
          .form-group.panel-body
            .row
              .col-md-4
                =label_tag "Phone Check Id"
              .col-md-8
                =text_field_tag :id, '',class: "form-control"
            %br/
            .text-center
              =submit_tag "Resend" , class: "btn btn-default"
  .col-md-4
    .panel.panel-default
      .panel-heading
        .panel-title.text-center
          Phone check confirmation
        =form_tag( phone_confirmation_calls_path(:phone_checks), multipart: true) do
          .form-group.panel-body
            .row
              .col-md-4
                =label_tag "Phone Check Id"
              .col-md-8
                =text_field_tag :id, '',class: "form-control"
            %br/
            .row
              .col-md-4
                =label_tag "PIN"
              .col-md-8
                =text_field_tag :pin_entered, '',class: "form-control"
            %br/
            .text-center
              =submit_tag "Submit Phone check confirmation" , class: "btn btn-default"
 
       

app/views/home/_investment_form.html.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      .panel-title.text-center
        Invest
    =form_tag( invest_call_path(:investments)) do
      .form-group.panel-body
        .row
          .col-md-4
            =label_tag "listing_id"
          .col-md-8
            =text_field_tag :listing_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "amount"
          .col-md-8
            =text_field_tag :amount, '',class: "form-control"
        %br/
        .text-center
          =submit_tag "Submit Investment" , class: "btn btn-default" 

     

app/views/home/_lead_listing_form.html.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      .panel-title.text-center
        Create Lead Listing 
    =form_tag( new_lead_listing_calls_path(:lead_listings)) do
      .form-group.panel-body
        .row
          .col-md-4
            =label_tag "loan_purpose_id"
          .col-md-8
            =text_field_tag :loan_purpose_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "amount"
          .col-md-8
            =text_field_tag :amount, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "fiat_amount"
          .col-md-8
            =text_field_tag :fiat_amount, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "currency_id"
          .col-md-8
            =text_field_tag :currency_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "term_days"
          .col-md-8
            =text_field_tag :term_days , '',class: "form-control"
        .row
          .col-md-4
            =label_tag "payment_type_id"
          .col-md-8
            =text_field_tag :payment_type_id 
        .row
          .col-md-4
            =label_tag "locale_id"
          .col-md-8
            =text_field_tag :locale_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "title"
          .col-md-8
            =text_field_tag :title, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "description"
          .col-md-8
            =text_field_tag :description, '',class: "form-control" 
        %br/
        .text-center
          =submit_tag "Submit Lead Listing" , class: "btn btn-default" 

     

app/views/home/_listings_form.html.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      .panel-title.text-center
        Create Listing
        
    =form_tag( new_listing_calls_path(:listings), multipart: true) do
      .form-group.panel-body
        .row
          .col-md-4
            =label_tag "loan_purpose_id"
          .col-md-8
            =text_field_tag :loan_purpose_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "amount"
          .col-md-8
            =text_field_tag :amount, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "currency_id"
          .col-md-8
            =text_field_tag :currency_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "term_days"
          .col-md-8
            =text_field_tag :term_days , '',class: "form-control"
        .row
          .col-md-4
            =label_tag "payment_type_id"
          .col-md-8
            =text_field_tag :payment_type_id 
        .row
          .col-md-4
            =label_tag "locale_id"
          .col-md-8
            =text_field_tag :locale_id, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "title"
          .col-md-8
            =text_field_tag :title, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "description"
          .col-md-8
            =text_field_tag :description, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "TFA Code"
          .col-md-8
            =text_field_tag :code, '',class: "form-control"
        .row
          .col-md-4
            =label_tag "Signature Picture"
          .col-md-8
            =file_field_tag :signature
        %br/
        .text-center
          =submit_tag "Submit Listing" , class: "btn btn-default" 

     

app/views/home/_user_changes_forms.html.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      .panel-title.text-center
        Bitcoin Address
      =form_tag( user_change_calls_path(:user_changes), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "New Bitcoin Address"
            .col-md-8
              =text_field_tag :new_value, '',class: "form-control"
          %br/
          .text-center
            =submit_tag "Submit Change Request" , class: "btn btn-default"

app/views/home/_withdraws_form.haml
.col-md-4
  .panel.panel-default
    .panel-heading
      .panel-title.text-center
        Withdraw
      =form_tag( withdraw_calls_path(:withdraws), multipart: true) do
        .form-group.panel-body
          .row
            .col-md-4
              =label_tag "Amount"
            .col-md-8
              =text_field_tag :amount, '',class: "form-control"
          .row
            .col-md-4
              =label_tag "Two Factor Code"
            .col-md-8
              =text_field_tag :code, '',class: "form-control"
          %br/
          .text-center
            =submit_tag "Withdraw" , class: "btn btn-default"

app/views/home/index.html.haml
%section
  .row
    .well
      .col-md-12  
        %p
          For more information please visit #{link_to "our repository", "https://github.com/btcjam/btcjam-client"} and our #{link_to "API FAQ", "https://btcjam.com/faq/api"}
          %br/
  .row
    .col-md-12
      .row
        - unless signed_in?
          .well
            .row
              .col-md-6
                .panel.panel-default
                  .panel-heading 
                    .panel-title.text-center
                      Sign in to explore the OAuth2 API  
                  .panel-body          
                    %p= link_to "Sign in with OAuth 2 provider", omniauth_authorize_path(:user, :btcjam, :manolo=>'pimpster'),  :class => "btn primary"
              .col-md-4.col-md-offset-2
                .panel.panel-default
                  .panel-heading 
                    .panel-title.text-center
                      Don't have an account? Create it!
                  .form-group.panel-body
           
                    =form_tag( new_user_calls_path(:users)) do
                      .row
                        .col-md-4
                          =label_tag "Username"
                        .col-md-8
                          =text_field_tag :username , '',class: "form-control"
                        .col-md-4
                          =label_tag "Password"
                        .col-md-8
                          =password_field_tag :password ,'',class: "form-control"
                        %br/
                        %br/
                        .col-md-12.text-center
                          =submit_tag "Create User" , class: "btn btn-default" 
          %br/ 
        - else
          %h2 BTCJam OAuth2 API
          .well 
            %p
              You are logged in as: <strong>#{current_user.oauth_info("alias")}</strong>
              %ul 
                %li BTCJam score: <strong>#{current_user.oauth_info("btcjam_score")}</strong> 
            %p
              = link_to "User Information", authenticated_calls_path(:me), :class => "btn", "data-explore" => []
              = link_to "My Open Listings", authenticated_calls_path(:my_open_listings), :class => "btn", "data-explore" => []
              = link_to "My Lead Listings", authenticated_calls_path(:lead_listings), :class => "btn", "data-explore" => []
              = link_to "My Receivables", authenticated_calls_path(:my_receivables), :class => "btn", "data-explore" => []
              = link_to "My Payables", authenticated_calls_path(:my_payables), :class => "btn", "data-explore" => []
              = link_to "References", authenticated_calls_path(:references), :class => "btn", "data-explore" => []
              = link_to "Multi Payments", authenticated_calls_path(:multi_payments), :class => "btn", "data-explore" => []
              = link_to "Invest", invest_call_path(:investments, {:listing_id => 34567, :amount => 1.1}), :class => "btn", "data-explore" => []
              = link_to "Sign out", "/logout", :class => "btn primary", :method => :delete 
            %br/
            %p
              = link_to "My ID Checks", authenticated_calls_path(:identity_checks), :class => "btn", "data-explore" => []
              = link_to "My Address Checks", authenticated_calls_path(:addr_checks), :class => "btn", "data-explore" => []
              = link_to "My Credit Checks", authenticated_calls_path(:credit_checks), :class => "btn", "data-explore" => []
              = link_to "My Phone Checks", authenticated_calls_path(:phone_checks), :class => "btn", "data-explore" => []
              = link_to "My User Changes", authenticated_calls_path(:user_changes), :class => "btn", "data-explore" => []
              = link_to "My Credit Report", authenticated_calls_path(:credit_report), :class => "btn", "data-explore" => []
            .row 
              .col-md-12
                %h3.text-center
                  Submit your documents via API
            = render partial: 'checks_forms'
            .row  
              = render partial: 'listings_form'
              = render partial: 'investment_form'
              = render partial: 'lead_listing_form'
            .row
              = render partial: 'activate_listing_form'
            .row
              = render partial: 'user_changes_forms'
            .row
              = render partial: 'withdraws_form'
             
    .col-md-12
      %h2 BTCJam JSON API
      .well
        %table.table.table-striped.table-bordered
          %thead
            %tr

              %th Request Format
          %tbody
            %tr

              %td https://btcjam.com/api/v1/listings?appid=[<strong>APP ID</strong>]&secret=[<strong>APP Secret</strong>]

        %p
        = link_to "Query All Open Listings", open_calls_path(:listings), :class => "btn", "data-explore" => []
        %br/
        %br/
        %br/


  .row
    .col-md-12
      %p
        %pre#display-json
          Select one of the api methods above
:javascript
  $( document ).ready(function() {
   populateLists("#{BTCJAM_APP_URL}",'listings', "#{BTCJAM_APP_ID}", "#{BTCJAM_APP_SECRET}")
  });

app/views/home/main.html.haml
%p
  = link_to "User Information", authenticated_calls_path(:me), :class => "btn", "data-explore" => []
  = link_to "My Open Listings", authenticated_calls_path(:my_open_listings), :class => "btn", "data-explore" => []
  = link_to "My Receivables", authenticated_calls_path(:my_receivables), :class => "btn", "data-explore" => []
  = link_to "My Payables", authenticated_calls_path(:my_payables), :class => "btn", "data-explore" => []
  = link_to "References", authenticated_calls_path(:references), :class => "btn", "data-explore" => []
  = link_to "Multi Payments", authenticated_calls_path(:multi_payments), :class => "btn", "data-explore" => []
  = link_to "Invest", invest_call_path(:investments, {:listing_id => 34567, :amount => 1.1}), :class => "btn", "data-explore" => []
  = link_to "Sign out", "/logout", :class => "btn primary", :method => :delete 
%br/
%p
  = link_to "My ID Checks", authenticated_calls_path(:identity_checks), :class => "btn", "data-explore" => []
  = link_to "My Address Checks", authenticated_calls_path(:addr_checks), :class => "btn", "data-explore" => []
  = link_to "My Credit Checks", authenticated_calls_path(:credit_checks), :class => "btn", "data-explore" => []
.row 
  .col-md-12
    %h3.text-center
      Submit your documents via API
= render partial: 'checks_forms'
.row  
  = render partial: 'listings_form'
  = render partial: 'investment_form'
  = render partial: 'lead_listing_form'